# Generated by Django 2.2.3 on 2019-07-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vilao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('categoria', models.CharField(max_length=10)),
                ('habilidades', models.TextField()),
                ('mortes', models.PositiveIntegerField()),
                ('armas', models.CharField(choices=[('machado', 'Machado'), ('escada', 'Escada'), ('espada', 'Espada'), ('tesoura', 'Tesoura'), ('veneno', 'Veneno'), ('pexera', 'Pexera'), ('serra elétrica', 'Serra Elétrica'), ('punhos', 'Punhos'), ('ak47', 'AK47'), ('almofada', 'Almofada'), ('outros', 'Outros'), ('desarmado', 'Desarmado')], max_length=20)),
                ('nivel_maldade', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('vivo', models.BooleanField(default=True)),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
    ]
